version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bemcomido_db
    environment:
      POSTGRES_DB: bemcomido
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - bemcomido_data:/var/lib/postgresql/data

volumes:
  bemcomido_data:
